### ISSUE TITLE
policy.no_grad is used for q target computation in SAC

### ISSUE THREAD

**Issue by syuntoku14** [cpnota/autonomous-learning-library#145]
Hi cpnota,

Although it may not affect the performance too much, I think this can be the wrong implementation when it is combined with polyak update.

Your SAC uses policy.no_grad for q target computation( https://github.com/cpnota/autonomous-learning-library/blob/68d355a86dac95a1204ec327250a2e7e9494d92c/all/agents/sac.py#L82 ).
According to the openai spinningup, the action should be output by policy.target.
https://github.com/openai/spinningup/blob/038665d62d569055401d91856abb287263096178/spinup/algos/pytorch/sac/sac.py#L191

Thank you!

**Comment by cpnota** [comment]
Hi syuntoku14,

I think it's correct as is. The relevant line in the spinning up implementation is: github.com/openai/spinningup/blob/038665d62d569055401d91856abb287263096178/spinup/algos/pytorch/sac/sac.py#L188

```python
        with torch.no_grad():
            # Target actions come from *current* policy
            a2, logp_a2 = ac.pi(o2)
```

Also notice in the pseudocode, only the Q and V networks use target networks. The policy network does not: https://spinningup.openai.com/en/latest/algorithms/sac.html

![SAC Pseudocode](https://spinningup.openai.com/en/latest/_images/math/c01f4994ae4aacf299a6b3ceceedfe0a14d4b874.svg)

We can also see here that in our implementation the policy network doesn't have a target network enabled: https://github.com/cpnota/autonomous-learning-library/blob/master/all/presets/continuous/sac.py#L97

```python
        policy = SoftDeterministicPolicy(
            policy_model,
            policy_optimizer,
            env.action_space,
            scheduler=CosineAnnealingLR(
                policy_optimizer,
                final_anneal_step
            ),
            writer=writer
        )
```

Thanks for the report though! Please continue to let me know of any issues you find!
