### ISSUE TITLE
Is close currently used?

### ISSUE THREAD

**Issue by mctigger** [cpnota/autonomous-learning-library#147]
https://github.com/cpnota/autonomous-learning-library/blob/e4fbe6e78e09671a02bbc2502634f355dbf36b4e/all/environments/abstract.py#L61

Using the search function I was not able to see whether env.close() is actually used somewhere.

**Comment by cpnota** [comment]
It's not used by anything directly in the library. It is necessary in some uses cases, for example, if you wanted to load multiple PyBullet environments in the same process.
