### ISSUE TITLE
Should env.step() return done and info?

### ISSUE THREAD

**Issue by mctigger** [cpnota/autonomous-learning-library#149]
https://github.com/cpnota/autonomous-learning-library/blob/68d355a86dac95a1204ec327250a2e7e9494d92c/all/environments/abstract.py#L42-L51

In the abstract Environment class it says that the step() methods should return the state, the reward, an indicator whether the episode ends and some information.

However, in the GymEnvironment only the reward and the state are returned: 
https://github.com/cpnota/autonomous-learning-library/blob/68d355a86dac95a1204ec327250a2e7e9494d92c/all/environments/gym.py#L44

Which usage should be the correct one?

**Comment by cpnota** [comment]
Ah, looks like the documentation is out of date. The State objective includes `done` and `info` now.
