### ISSUE TITLE
GaussianPolicy uses tanh two times

### ISSUE THREAD

**Issue by mctigger** [cpnota/autonomous-learning-library#154]
Hey,
can you explain to me why tanh is used here:
https://github.com/cpnota/autonomous-learning-library/blob/6d1111afce0d1582de463326f7d078a86e850551/all/policies/gaussian.py#L51-L61

and in _sqash ?

Thank you :)

**Comment by cpnota** [comment]
Looks like a bug 😅 Thanks for the report! I'll open a PR with a fix.

**Comment by mctigger** [comment]
@cpnota Maybe it would be also good to implement it like here: https://github.com/danijar/dreamer/issues/4

But I am not sure how much of a difference it makes in practice!

**Comment by mctigger** [comment]
Nvm, I see this is already implemented here: https://github.com/cpnota/autonomous-learning-library/blob/master/all/policies/soft_deterministic.py
