### ISSUE TITLE
[VAC] No reset after episode end?

### ISSUE THREAD

**Issue by mctigger** [cpnota/autonomous-learning-library#156]
Hi @cpnota,
I was just wondering what happens at the end of an episode? Afaik the end of an episode is not registered by the agent and so ```self._features``` is never reset. At the end of an episode the last state features is used to calculate the value-target for the first state of the next episode and leads to wrong value targets? 

https://github.com/cpnota/autonomous-learning-library/blob/3ec67d5c05c521344bbba47045c1b179a8ccc275/all/agents/vac.py#L31-L38

**Comment by cpnota** [comment]
Hi @mctigger ,

Checkout out ```_train```:

https://github.com/cpnota/autonomous-learning-library/blob/3ec67d5c05c521344bbba47045c1b179a8ccc275/all/agents/vac.py#L41-L57

That's value *target* also is recomputed. For the previous state (which we are updating the policy/value function for) we always use ```self._features```. The key is that the function approximator "zeros out" the output of `v` and `policy` when a `state` is a terminal state, so there is no gradient and no update is performed.
