### ISSUE TITLE
Make run_experiment more modular

### ISSUE THREAD

**Issue by mctigger** [cpnota/autonomous-learning-library#162]
https://github.com/cpnota/autonomous-learning-library/blob/3ec67d5c05c521344bbba47045c1b179a8ccc275/all/experiments/run_experiment.py#L5-L13

`run_experiment` should only take `agents`, `envs` and `experiment`. Then we could call it like this:

```python3
def make_experiment(agent, env):
    return CustomExperiment(
        agent, env, render=False, quiet=False, write_loss=True # Allows for any interface
    )

run_experiment(
         agents, envs, make_experiment
)
```

**Comment by michalgregor** [comment]
I think it would also be useful if run_experiment returned something - possibly the experiment object itself. Useful e.g. when you want to visualise the curves from the tensorboard log. Right now you don't even know what directory they're in if you are using run_experiment, right?

**Comment by cpnota** [comment]
Will address as part of #290
