### ISSUE TITLE
[Question] Change output path

### ISSUE THREAD

**Issue by heyt0ny** [cpnota/autonomous-learning-library#174]
Hello!

Really clean and good looking RL lib for Pytorch. I tried all of them, and that's the most I liked so far!

However I wonder how to change output folder path. Seems like I need to change  the `log_path`, defined inside `ExperimentWriter` class, but I guess there is no way to overwrite it, without changing all the `run_experiment` internals?

**Comment by cpnota** [comment]
Hi, thanks for the feedback!

You are right, there is no easy way to change it at the moment. If you have an immediate need for it, we'd be happy to put in a hotfix! It should be easy to add an optional parameter to the `run_experiment` API.

**Comment by heyt0ny** [comment]
Thanks, would be great !

**Comment by cpnota** [comment]
Added!
