### ISSUE TITLE
Unused variables in atari_wrappers.py

### ISSUE THREAD

**Issue by justinkterry** [cpnota/autonomous-learning-library#178]
justinkterry@preacherMan environments % flake8 --ignore "E501,E731,E74,E402,F401,W503,E128"
./atari_wrappers.py:58:27: E221 multiple spaces before operator
./atari_wrappers.py:77:30: F821 undefined name 'kwargs'
./atari_wrappers.py:80:36: F821 undefined name 'kwargs'
./atari_wrappers.py:85:16: F821 undefined name 'lives'
./atari_wrappers.py:85:39: F821 undefined name 'lives'

**Comment by justinkterry** [comment]
@cpnota This was closed by mistake.

**Comment by cpnota** [comment]
Closed with #183
