### ISSUE TITLE
Rename MultiagentPettingZooEnv

### ISSUE THREAD

**Issue by jkterry1** [cpnota/autonomous-learning-library#229]
MultiagentPettingZooEnv is an odd and redundant name.  This should probably just be MultiagentEnv.

**Comment by justinkterry** [comment]
MultiagentEnvExperiment should also probably be MultiagentExperiment

**Comment by cpnota** [comment]
I'm closing this on the basis that `MultiagentEnvironment` is the abstract class, and we might want implementations that are not petting-zoo based. The current `MultiagentPettingZooEnvironment` is tightly coupled with the PettingZoo api.
