### ISSUE TITLE
Warning for multiagent

### ISSUE THREAD

**Issue by benblack769** [cpnota/autonomous-learning-library#230]
There is a try-catch block here that emits a warning when using the multi-agent preset. The warning is created because creating a pytorch tensor out of a list of strings gives a ValueError.

Its not ideal that a warning is emitted with standard usage. An alternative is to have an if statement to explicitly catch that case. Something like

```
elif isinstance(v, str):
    ...
```

**Comment by cpnota** [comment]
I'm not sure the context here, so closing for now.
