### ISSUE TITLE
AutoROM changes

### ISSUE THREAD

**Issue by benblack769** [cpnota/autonomous-learning-library#263]
AutoROM is changing to support Jesse's gym support in ale-py: https://github.com/mgbellemare/Arcade-Learning-Environment/pull/382 

More links here: https://github.com/cpnota/autonomous-learning-library/pull/262

These changes will likely break ALL's CI.

In particular, the paths to which AutoROM saves roms is different. However, the latest pettingzoo release will work.

The only thing that will need to change is the way that atari-py uses roms. I think the alternatives are:

1. To install and pin an earlier version of atari-py which includes the ROMs or
2. To make a custom script/command to distribute the files from the new autorom to atari-py (note that we are intentionally not providing explicit support for atari-py to aid the deprecation of atari-py in favor of ale-pypi.

Just letting you know what is going on here.

**Comment by cpnota** [comment]
Closed by #268
