### ISSUE TITLE
SAC and DDPG parameters for 'Hopper-v3' from Mujoco

### ISSUE THREAD

**Issue by Will-Nie** [cpnota/autonomous-learning-library#264]
HI, I recently ran 'Hopper-v3' from mujoco_py (license is free to obtain now) in autonomous-learning-library by adopting the default setting from pybullet 'HopperBulletEnv-v0' and plotted the results as follows: (SAC was the algo I used)

<img width="1340" alt="Screenshot 2022-01-05 at 3 33 22 PM" src="https://user-images.githubusercontent.com/61083608/148246484-7e97dacb-0d02-4770-9bb6-9d71a28df500.png">

It seems the parameters can not be simply adopted from 'HopperBulletEnv-v0' to run 'Hopper-v3' since normally the score would reach 3000 after 1~2m env step. May I ask if you could make a set of parameters for Hopper-v3 for the algorithm sac and ddpg. Thanks in advance!

**Comment by cpnota** [comment]
Will try to re-tune this for the v4 mujoco environments.

**Comment by cpnota** [comment]
I updated the default hyperparameters in #312. For a 2 million step hopper training:

<img width="1070" alt="image" src="https://github.com/cpnota/autonomous-learning-library/assets/2100334/eb800b1f-494d-4f54-bb08-dba027c5b19d">
