### ISSUE TITLE
README.md installation instructions refers to non existent `pytorch` extras

### ISSUE THREAD

**Issue by sonelu** [cpnota/autonomous-learning-library#265]
Hi,

First, thanks for starting this project. I really enjoy some of the design decisions you have made and I will try to participate in the it.

I will raise a few defects for small, but annoying things, that probably have been left behind as the project moved on.

This issue is about this line in the README.md that refers to an non-existing extras `pytorch` and should probably be removed.

https://github.com/cpnota/autonomous-learning-library/blob/aaa5403ead52f1175b460fc3984864355c575061/README.md?plain=1#L66

**Comment by cpnota** [comment]
closed by #270
